# Generated by Django 4.2 on 2023-05-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-price'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'brand'], name='adsapi_prod_name_f73a56_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='adsapi_prod_price_f65c39_idx'),
        ),
    ]
